version: 0.2

phases:
  pre_build:
    commands:
      - echo "Setting AWS region and EKS cluster in pre-build stage..."
      - echo "Checking eksctl and kubectl versions..."
      - eksctl version
      - kubectl version --client=true
  build:
    commands:
      - echo "Setting kubectl config for EKS..."
      - aws eks update-kubeconfig --region $AWS_DEFAULT_REGION --name $EKS_CLUSTER_NAME
      - echo "Applying Kubernetes manifests..."
      - kubectl apply -f k8s/deployment.yaml
artifacts:
  files:
    - '**/*'
