version: 0.2

phases:
  pre_build:
    commands:
      - echo Setting AWS region and EKS cluster from environment variables...
      - echo "Region: $AWS_DEFAULT_REGION"
      - echo "EKS Cluster Name: $EKS_CLUSTER_NAME"
      - echo Checking installed versions of eksctl and kubectl...
      - eksctl version
      - kubectl version --client

  build:
    commands:
      - echo Updating kubeconfig for the EKS cluster...
      - aws eks update-kubeconfig --region $AWS_DEFAULT_REGION --name $EKS_CLUSTER_NAME
      - echo Applying Kubernetes manifest...
      - kubectl apply -f k8s/deployment.yaml

  post_build:
    commands:
      - echo Build and deployment process completed successfully!

artifacts:
  files:
    - '**/*'
