version: 0.2

phases:
  pre_build:
    commands:
      - echo "Setting AWS region and EKS cluster in pre_build stage..."
      - aws eks --region $AWS_DEFAULT_REGION update-kubeconfig --name $EKS_CLUSTER_NAME

  build:
    commands:
      - echo "Deploying to EKS..."
      - kubectl apply -f k8s/deployment.yaml
      - kubectl apply -f k8s/service.yaml

  post_build:
    commands:
      - echo "Deployment completed successfully."
